<?php

return [
    'validation_error' => 'Wystąpił błąd w co najmniej jednym polu w żądaniu.',
    'errors' => [
        'return' => 'Powróc do poprzedniej strony',
        'home' => 'Go Home',
        '403' => [
            'header' => 'Forbidden',
            'desc' => 'Nie masz uprawnień dostępu do tego zasobu na tym serwerze.',
        ],
        '404' => [
            'header' => 'Nie znaleziono pliku',
            'desc' => 'Nie mogliśmy zlokalizować żądanego zasobu na serwerze.',
        ],
        'installing' => [
            'header' => 'Instalacja serwera',
            'desc' => 'Żądany serwer nadal kończy proces instalacji. Sprawdź ponownie za kilka minut. Po zakończeniu tego procesu powinieneś otrzymać wiadomość e-mail.',
        ],
        'suspended' => [
            'header' => 'Serwer zawieszony',
            'desc' => 'Ten serwer został zawieszony i nie można uzyskać do niego dostępu.',
        ],
        'maintenance' => [
            'header' => 'Węzeł w trakcie konserwacji',
            'title' => 'Chwilowo niedostępny',
            'desc' => 'Ten węzeł jest w trakcie konserwacji, dlatego tymczasowo nie można uzyskać dostępu do serwera.',
        ],
    ],
    'index' => [
        'header' => 'Twoje serwery',
        'header_sub' => 'Serwery, do których masz dostęp.',
        'list' => 'Lista serwerów',
    ],
    'api' => [
        'index' => [
            'list' => 'Your Keys',
            'header' => 'Account API',
            'header_sub' => 'Manage access keys that allow you to perform actions against the panel.',
            'create_new' => 'Create New API key',
            'keypair_created' => 'An API key has been successfully generated and is listed below.',
        ],
        'new' => [
            'header' => 'New API Key',
            'header_sub' => 'Create a new account access key.',
            'form_title' => 'Details',
            'descriptive_memo' => [
                'title' => 'Description',
                'description' => 'Enter a brief description of this key that will be useful for reference.',
            ],
            'allowed_ips' => [
                'title' => 'Allowed IPs',
                'description' => 'Enter a line delimited list of IPs that are allowed to access the API using this key. CIDR notation is allowed. Leave blank to allow any IP.',
            ],
        ],
    ],
    'account' => [
        'details_updated' => 'Szczegóły Twojego konta zostały zaktualizowane.',
        'invalid_password' => 'Hasło podane do Twojego konta jest nieprawidłowe.',
        'header' => 'Twoje konto',
        'header_sub' => 'Zarządzaj danymi swojego konta.',
        'update_pass' => 'Zmień hasło',
        'update_email' => 'Zmień adres e-mail',
        'current_password' => 'Aktualne hasło',
        'new_password' => 'Howe hasło',
        'new_password_again' => 'Powtórz nowe hasło',
        'new_email' => 'Nowy adres e-mail',
        'first_name' => 'Imię',
        'last_name' => 'Nazwisko',
        'update_identity' => 'Zaktualizuj tożsamość',
        'username_help' => 'Twoja nazwa użytkownika musi być unikalna dla Twojego konta i może zawierać tylko następujące znaki: :requirements.',
        'language' => 'Język',
    ],
    'security' => [
        'session_mgmt_disabled' => 'Your host has not enabled the ability to manage account sessions via this interface.',
        'header' => 'Account Security',
        'header_sub' => 'Control active sessions and 2-Factor Authentication.',
        'sessions' => 'Active Sessions',
        '2fa_header' => '2-Factor Authentication',
        '2fa_token_help' => 'Enter the 2FA Token generated by your app (Google Authenticator, Authy, etc.).',
        'disable_2fa' => 'Disable 2-Factor Authentication',
        '2fa_enabled' => '2-Factor Authentication is enabled on this account and will be required in order to login to the panel. If you would like to disable 2FA, simply enter a valid token below and submit the form.',
        '2fa_disabled' => '2-Factor Authentication is disabled on your account! You should enable 2FA in order to add an extra level of protection on your account.',
        'enable_2fa' => 'Enable 2-Factor Authentication',
        '2fa_qr' => 'Configure 2FA on Your Device',
        '2fa_checkpoint_help' => 'Use the 2FA application on your phone to take a picture of the QR code to the left, or manually enter the code under it. Once you have done so, generate a token and enter it below.',
        '2fa_disable_error' => 'The 2FA token provided was not valid. Protection has not been disabled for this account.',
    ],
];
